export const ar = {
  // Auth Page
  auth: {
    title: 'نظام إدارة المشاريع',
    subtitle: 'إدارة العقارات والإنشاءات',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    demoEmail: 'demo@example.com',
    demoPassword: 'Demo1234!',
    haveAccount: 'هل لديك حساب؟',
    noAccount: 'ليس لديك حساب؟',
    demoCredentials: 'بيانات العرض التوضيحي:',
    autoLoadData: 'قم بالتسجيل لتحميل بيانات العينة تلقائياً',
    loading: 'يرجى الانتظار...',
    authFailed: 'فشل التحقق من الهوية',
  },

  // Navigation
  nav: {
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    salesUnits: 'المبيعات والوحدات',
    hrPayroll: 'الموارد البشرية والرواتب',
    inventory: 'المخزون',
    suppliers: 'الموردون',
    projects: 'المشاريع',
  },

  // Dashboard
  dashboard: {
    title: 'نظرة عامة على لوحة التحكم',
    activeProjects: 'المشاريع النشطة',
    of: 'من',
    unitsSold: 'الوحدات المباعة',
    total: 'المجموع',
    totalRevenue: 'إجمالي الإيرادات',
    collected: 'تم التحصيل',
    totalCosts: 'إجمالي التكاليف',
    invested: 'مستثمرة',
    grossProfit: 'الربح الإجمالي',
    margin: 'الهامش',
    unitInventory: 'مخزون الوحدات',
    available: 'متاح',
    reserved: 'محجوز',
    sold: 'مباع',
    paymentStatus: 'حالة الدفع',
    pending: 'قيد الانتظار',
    overdue: 'متأخر',
    financialSummary: 'الملخص المالي',
    revenue: 'الإيرادات',
    costs: 'التكاليف',
    netProfit: 'صافي الربح',
  },

  // Real Estate Units
  units: {
    title: 'الوحدات العقارية',
    addUnit: 'إضافة وحدة',
    unitCode: 'رمز الوحدة',
    unitName: 'اسم الوحدة',
    unitType: 'نوع الوحدة',
    apartment: 'شقة',
    villa: 'فيلا',
    land: 'أرض',
    price: 'السعر',
    area: 'المساحة',
    sqm: 'متر مربع',
    bedrooms: 'غرف النوم',
    bathrooms: 'الحمامات',
    location: 'الموقع',
    selectProject: 'اختر المشروع',
    status: 'الحالة',
    available: 'متاح',
    reserved: 'محجوز',
    sold: 'مباع',
    saveUnit: 'حفظ الوحدة',
    view: 'عرض',
    cancel: 'إلغاء',
  },

  // Sales Contracts
  contracts: {
    title: 'عقود المبيعات',
    newContract: 'عقد جديد',
    contractNumber: 'رقم العقد',
    selectCustomer: 'اختر العميل',
    selectUnit: 'اختر الوحدة',
    contractDate: 'تاريخ العقد',
    dueDate: 'تاريخ الاستحقاق',
    downPaymentPercent: 'نسبة الدفعة الأولى',
    unitPrice: 'سعر الوحدة',
    downPayment: 'الدفعة الأولى',
    remaining: 'المتبقي',
    collection: 'التحصيل',
    active: 'نشط',
    completed: 'مكتمل',
    viewInstallments: 'عرض الأقساط',
    createContract: 'إنشاء عقد',
  },

  // Payments
  payments: {
    title: 'أقساط الدفع',
    newInstallment: 'قسط جديد',
    installmentPayments: 'مدفوعات الأقساط',
    dueDate: 'تاريخ الاستحقاق',
    amount: 'المبلغ',
    installmentNum: 'رقم القسط',
    createInstallment: 'إنشاء قسط',
    recordPayment: 'تسجيل دفعة',
    paid: 'تم الدفع',
    outstanding: 'متبقي',
    overdue: 'متأخر',
    pending: 'قيد الانتظار',
    overduAlert: 'تنبيه الأقساط المتأخرة',
    overdueInstallments: 'أقساط متأخرة',
  },

  // Customers
  customers: {
    title: 'العملاء',
    addCustomer: 'إضافة عميل',
    name: 'الاسم',
    contactPerson: 'جهة الاتصال',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    address: 'العنوان',
    status: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    suspended: 'معلق',
  },

  // HR
  hr: {
    title: 'الموارد البشرية',
    employees: 'الموظفون',
    addEmployee: 'إضافة موظف',
    attendance: 'الحضور',
    recordAttendance: 'تسجيل الحضور',
    payroll: 'الرواتب',
    createPayroll: 'إنشاء رصيد راتب',
    reports: 'التقارير',
    firstName: 'الاسم الأول',
    lastName: 'الاسم الأخير',
    position: 'المنصب',
    department: 'القسم',
    salary: 'الراتب',
    joiningDate: 'تاريخ الانضمام',
    attendanceDate: 'تاريخ الحضور',
    checkIn: 'الدخول',
    checkOut: 'الخروج',
    present: 'حاضر',
    absent: 'غائب',
    late: 'متأخر',
    baseSalary: 'الراتب الأساسي',
    bonuses: 'المكافآت',
    deductions: 'الخصومات',
    netSalary: 'الراتب الصافي',
    status: 'الحالة',
  },

  // Inventory
  inventory: {
    title: 'المخزون والمستودعات',
    warehouses: 'المستودعات',
    addWarehouse: 'إضافة مستودع',
    items: 'العناصر',
    addItem: 'إضافة عنصر',
    reports: 'التقارير',
    warehouseName: 'اسم المستودع',
    location: 'الموقع',
    manager: 'المدير',
    capacity: 'السعة',
    itemCode: 'رمز العنصر',
    itemName: 'اسم العنصر',
    quantity: 'الكمية',
    unit: 'الوحدة',
    reorderLevel: 'مستوى إعادة الترتيب',
    unitCost: 'تكلفة الوحدة',
    movement: 'الحركة',
    in: 'داخل',
    out: 'خارج',
    reason: 'السبب',
  },

  // Suppliers
  suppliers: {
    title: 'الموردون والمقاولون',
    suppliers: 'الموردون',
    addSupplier: 'إضافة مورد',
    contractors: 'المقاولون',
    addContractor: 'إضافة مقاول',
    invoices: 'الفواتير',
    purchaseInvoices: 'فواتير الشراء',
    newInvoice: 'فاتورة جديدة',
    statements: 'البيانات',
    contractorStatements: 'بيانات المقاول',
    newStatement: 'بيان جديد',
    supplierName: 'اسم المورد',
    classification: 'التصنيف',
    materials: 'المواد',
    services: 'الخدمات',
    contact: 'جهة الاتصال',
    invoiceNumber: 'رقم الفاتورة',
    invoiceDate: 'تاريخ الفاتورة',
    amount: 'المبلغ',
    paidAmount: 'المبلغ المدفوع',
    outstanding: 'المتبقي',
    progress: 'التقدم',
  },

  // Projects
  projects: {
    title: 'مشاريع العقارات',
    projects: 'المشاريع',
    newProject: 'مشروع جديد',
    phases: 'المراحل',
    addPhase: 'إضافة مرحلة',
    costs: 'التكاليف',
    projectCosts: 'تكاليف المشروع',
    addCost: 'إضافة تكلفة',
    reports: 'التقارير',
    projectCode: 'رمز المشروع',
    projectName: 'اسم المشروع',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    expectedCompletion: 'التاريخ المتوقع للانتهاء',
    budget: 'الميزانية',
    status: 'الحالة',
    planning: 'التخطيط',
    active: 'نشط',
    completed: 'مكتمل',
    phaseName: 'اسم المرحلة',
    phaseNumber: 'رقم المرحلة',
    costCategory: 'فئة التكلفة',
    estimatedCost: 'التكلفة المقدرة',
    actualCost: 'التكلفة الفعلية',
  },

  // Common Actions
  actions: {
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    view: 'عرض',
    add: 'إضافة',
    create: 'إنشاء',
    update: 'تحديث',
    confirm: 'تأكيد',
    close: 'إغلاق',
    submit: 'إرسال',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    import: 'استيراد',
  },

  // Messages
  messages: {
    loading: 'جاري التحميل...',
    success: 'تم بنجاح',
    error: 'حدث خطأ',
    confirmDelete: 'هل تأكد من الحذف؟',
    noData: 'لا توجد بيانات',
    emptyFields: 'يرجى ملء جميع الحقول المطلوبة',
  },
};
