export const ar = {
  // Auth Page
  auth: {
    title: 'نظام إدارة المشاريع',
    subtitle: 'إدارة العقارات والإنشاءات',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    demoEmail: 'demo@example.com',
    demoPassword: 'Demo1234!',
    haveAccount: 'هل لديك حساب؟',
    noAccount: 'ليس لديك حساب؟',
    demoCredentials: 'بيانات العرض التوضيحي:',
    autoLoadData: 'قم بالتسجيل لتحميل بيانات العينة تلقائياً',
    loading: 'يرجى الانتظار...',
    authFailed: 'فشل التحقق من الهوية',
  },

  // Navigation
  nav: {
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    salesUnits: 'المبيعات والوحدات',
    hrPayroll: 'الموارد البشرية والرواتب',
    inventory: 'المخزون',
    suppliers: 'الموردون',
    projects: 'المشاريع',
  },

  // Dashboard
  dashboard: {
    title: 'نظرة عامة على لوحة التحكم',
    activeProjects: 'المشاريع النشطة',
    of: 'من',
    unitsSold: 'الوحدات المباعة',
    total: 'المجموع',
    totalRevenue: 'إجمالي الإيرادات',
    collected: 'تم التحصيل',
    totalCosts: 'إجمالي التكاليف',
    invested: 'مستثمرة',
    grossProfit: 'الربح الإجمالي',
    margin: 'الهامش',
    unitInventory: 'مخزون الوحدات',
    available: 'متاح',
    reserved: 'محجوز',
    sold: 'مباع',
    paymentStatus: 'حالة الدفع',
    pending: 'قيد الانتظار',
    overdue: 'متأخر',
    financialSummary: 'الملخص المالي',
    revenue: 'الإيرادات',
    costs: 'التكاليف',
    netProfit: 'صافي الربح',
  },

  // Real Estate Units
  units: {
    title: 'الوحدات العقارية',
    addUnit: 'إضافة وحدة',
    unitCode: 'رمز الوحدة',
    unitName: 'اسم الوحدة',
    unitType: 'نوع الوحدة',
    apartment: 'شقة',
    villa: 'فيلا',
    land: 'أرض',
    price: 'السعر',
    area: 'المساحة',
    sqm: 'متر مربع',
    bedrooms: 'غرف النوم',
    bathrooms: 'الحمامات',
    location: 'الموقع',
    selectProject: 'اختر المشروع',
    status: 'الحالة',
    available: 'متاح',
    reserved: 'محجوز',
    sold: 'مباع',
    saveUnit: 'حفظ الوحدة',
    view: 'عرض',
    cancel: 'إلغاء',
  },

  // Sales Contracts
  contracts: {
    title: 'عقود المبيعات',
    newContract: 'عقد جديد',
    contractNumber: 'رقم العقد',
    selectCustomer: 'اختر العميل',
    selectUnit: 'اختر الوحدة',
    contractDate: 'تاريخ العقد',
    dueDate: 'تاريخ الاستحقاق',
    downPaymentPercent: 'نسبة الدفعة الأولى',
    unitPrice: 'سعر الوحدة',
    downPayment: 'الدفعة الأولى',
    remaining: 'المتبقي',
    collection: 'التحصيل',
    active: 'نشط',
    completed: 'مكتمل',
    viewInstallments: 'عرض الأقساط',
    createContract: 'إنشاء عقد',
  },

  // Payments
  payments: {
    title: 'أقساط الدفع',
    newInstallment: 'قسط جديد',
    installmentPayments: 'مدفوعات الأقساط',
    dueDate: 'تاريخ الاستحقاق',
    amount: 'المبلغ',
    installmentNum: 'رقم القسط',
    createInstallment: 'إنشاء قسط',
    recordPayment: 'تسجيل دفعة',
    paid: 'تم الدفع',
    outstanding: 'متبقي',
    overdue: 'متأخر',
    pending: 'قيد الانتظار',
    overduAlert: 'تنبيه الأقساط المتأخرة',
    overdueInstallments: 'أقساط متأخرة',
  },

  // Customers
  
    title: 'العملاء',
    addCustomer: 'إضافة عميل',
    name: 'الاسم',
    contactPerson: 'جهة الاتصال',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    address: 'العنوان',
    status: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    suspended: 'معلق',
  

  // HR
  hr: {
    title: 'الموارد البشرية',
    employee : 'الموظف',
    Resigned : 'استقال',
    Terminated : 'تم إنهاؤه',
    Present : 'حاضر',
    Absent : 'غائب',
    Late : 'متأخر',
    HalfDay : 'نصف يوم',
    attendanceTracking: 'تتبع الحضور',
    employees: 'الموظفون',
    addEmployee: 'إضافة موظف',
    payrollManagement: 'إدارة الرواتب',
    reports: 'التقارير',
    employeeID: 'معرف الموظف',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    position: 'المنصب',
    department: 'القسم',
    salary: 'الراتب',
    joiningDate: 'تاريخ الانضمام',
    attendance: 'الحضور',
    recordAttendance: 'تسجيل الحضور',
    payroll: 'الرواتب',
    createPayroll: 'إنشاء رصيد راتب',
   selectEmployee: 'اختر الموظف',
    payPeriodStart: 'بداية فترة الدفع',
    payPeriodEnd: 'نهاية فترة الدفع',
    attendanceDate: 'تاريخ الحضور',
    checkIn: 'الدخول',
    checkOut: 'الخروج',
    present: 'حاضر',
    absent: 'غائب',
    late: 'متأخر',
    Period: 'الفترة',
    Base: 'الأساسي',
    Bonus: 'المكافأة',
    Deductions: 'الخصومات',
    baseSalary: 'الراتب الأساسي',
    bonuses: 'المكافآت',
    deductions: 'الخصومات',
    netSalary: 'الراتب الصافي',
    net: 'الصافي',
    status: 'الحالة',
    totalEmployees: 'إجمالي الموظفين',
    activeEmployees: 'الموظفون النشطون',
    suspendedEmployees: 'الموظفون المعلقون',
    resignedEmployees: 'الموظفون المستقيلون',
    totalPayrollAmount: 'إجمالي مبلغ الرواتب',
    employeeStatusSummary: 'ملخص حالة الموظف',
  },
loading: 'جاري التحميل...',
hrReportsAnalytics: 'تقارير وتحليلات الموارد البشرية',
  // Inventory
  inventory: {
    title: 'المخزون والمستودعات',
    warehouses: 'المستودعات',
    addWarehouse: 'إضافة مستودع',
    contactperson: 'جهة الاتصال',
    warehouseList: 'قائمة المستودعات',
    actions: 'الإجراءات',
    warehouse: 'المستودع',
    editWarehouse: 'تعديل المستودع',
    saveWarehouse: 'حفظ المستودع',
    status: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    items: 'العناصر',
    addItem: 'إضافة عنصر',
    itemtype: 'نوع العنصر',
    belowreorderlevel: 'عناصر تحت مستوى إعادة الترتيب  ',
    CurrentStock: 'المخزون الحالي',
    Shortage: 'النقص',
    inventoryReports: 'تقارير المخزون',
    totalItems: 'إجمالي العناصر',
    lowStockItems: 'العناصر منخفضة المخزون',
    totalQuantity: 'إجمالي الكمية',
    totalValue: 'القيمة الإجمالية',
    inventory: 'المخزون',
    totalitems: 'إجمالي العناصر',
    lowstockitems: 'العناصر منخفضة المخزون',
    totalquantity: 'إجمالي الكمية',
    totalvalue: 'القيمة الإجمالية',
    reports: 'التقارير',
    warehouseName: 'اسم المستودع',
    selecteaWarehouse: 'اختر مستودع',
    location: 'الموقع',
    manager: 'المدير',
    capacity: 'السعة',
    itemCode: 'رمز العنصر',
    itemName: 'اسم العنصر',
    quantity: 'الكمية',
    unit: 'الوحدة',
    movements: 'الحركات',
    RecordStockMovement: 'تسجيل حركة المخزون',
    movementType: 'نوع الحركة',
    selectMovementType: 'اختر نوع الحركة',
    in: 'وارد',
    out: 'صادر',
    Adjustment: 'تعديل',
    movementQuantity: 'كمية الحركة',
    movementDate: 'تاريخ الحركة',
    createMovement: 'إنشاء حركة',
    unittype: 'نوع الوحدة (قطع، كجم، لترات، إلخ)',
    reorderLevel: 'مستوى إعادة الترتيب',
    unitCost: 'تكلفة الوحدة',
    movement: 'الحركة',
    reason: 'السبب',
  },

  // Suppliers
  suppliers: {
    title: 'الموردون والمقاولون',
    suppliers: 'الموردون',
    addSupplier: 'إضافة مورد',
    Classification: 'التصنيف',
    editesupplier: 'تعديل المورد',
    NewStatement: 'بيان جديد',
    selectContractor: 'اختر مقاول',
    SelectContract: 'اختر عقد',
    supplierManagement: 'إدارة الموردين',
    contractorManagement: 'إدارة المقاولين',
    supplierReports: 'تقارير الموردين',
    contractorReports: 'تقارير المقاولين',
    totalContractors: 'إجمالي المقاولين',
    activeContractors: 'المقاولون النشطون',
    inactiveContractors: 'المقاولون غير النشطين',
    blacklistedContractors: 'المقاولون المدرجون في القائمة السوداء',
    totalSuppliers: 'إجمالي الموردين',
    activeSuppliers: 'الموردون النشطون',
    inactiveSuppliers: 'الموردون غير النشطين',
    blacklistedSuppliers: 'الموردون المدرجون في القائمة السوداء',
    contractorName: 'اسم المقاول',
    supplierName: 'اسم المورد',
    totalContracts: 'إجمالي العقود',
    totalInvoices: 'إجمالي الفواتير',
    totalPayments:' إجمالي المدفوعات',
    Outstanding: 'المتبقي',
    ContractorStatements: 'بيانات المقاول',
    ProgressPercentage: 'نسبة التقدم',
    contractors: 'المقاولون',
    AmountPaid: 'المبلغ المدفوع',
    RecordPayment: 'تسجيل دفعة',
    selectsupplier: 'اختر مورد',
    invoice_number: 'رقم الفاتورة',
    invoice_date: 'تاريخ الفاتورة',
    due_date: 'تاريخ الاستحقاق',
    amount: 'المبلغ',
    AmountClaimed: 'المبلغ المطالب به',
    licenseNumber: 'رقم الرخصة',
    contactPerson: 'جهة الاتصال',
    insuranceInfo: 'معلومات التأمين',
    active: 'نشط',
    inactive: 'غير نشيط',
    blacklisted: 'مدرج في القائمة السوداء',
    createStatement: 'إنشاء بيان',
    contractnumber: 'رقم العقد',
    addContractor: 'إضافة مقاول',
    invoices: 'الفواتير',
    purchaseInvoices: 'فواتير الشراء',
    newInvoice: 'فاتورة جديدة',
    statements: 'البيانات',
    contractorStatements: 'بيانات المقاول',
    newStatement: 'بيان جديد',
    editcontractor: 'تعديل المقاول',
    supplierStatements: 'بيانات المورد',
    supplier: 'المورد',
    classification: 'التصنيف',
    materials: 'المواد',
    dueDate: 'تاريخ الاستحقاق',
    description: 'الوصف',
    Materials: 'المواد',
    Services: 'الخدمات',
    taxId: 'الرقم الضريبي',
    services: 'الخدمات',
    contact: 'جهة الاتصال',
    invoiceNumber: 'رقم الفاتورة',
    invoiceDate: 'تاريخ الفاتورة',
    addinvoice: 'إضافة فاتورة',
    save_invoice: 'حفظ الفاتورة',
    invoice: 'الفاتورة',
    totalamount: 'المبلغ الإجمالي',
    purchase_invoices: 'فواتير الشراء',
    paidamount: 'المبلغ المدفوع',
    Progress: 'التقدم',
    createinvoice: 'إنشاء فاتورة',
    paidAmount: 'المبلغ المدفوع',
    outstanding: 'المتبقي',
    progress: 'التقدم',
    totalAmount: 'المبلغ الإجمالي',
  },

  // Projects
  projects: {
    title: 'مشاريع العقارات',
    projects: 'المشاريع',
    timeline: 'الجدول الزمني',
    phase: 'المرحلة',
    RealEstateProjects: 'مشاريع العقارات',
    ProjectReportsAnalytics: 'تقارير وتحليلات المشاريع',
    totalproject: 'إجمالي المشاريع',
    activeProjects: 'المشاريع النشطة',
    completedProjects: 'المشاريع المكتملة',
    totalBudget: 'إجمالي الميزانية',
    budgetUtilization: 'استخدام الميزانية',
    remainingBudget: 'الميزانية المتبقية',
    totalSpent: 'إجمالي المصروفات',
    location: 'الموقع',
    newProject: 'مشروع جديد',
    phases: 'المراحل',
    addPhase: 'إضافة مرحلة',
    costs: 'التكاليف',
    projectCosts: 'تكاليف المشروع',
    addCost: 'إضافة تكلفة',
    reports: 'التقارير',
    projectCode: 'رمز المشروع',
    projectName: 'اسم المشروع',
    projectType: 'نوع المشروع',
    description: 'الوصف',
    summaryproject: 'ملخص المشروع',
    AmountSpent: 'المبلغ المصروف',
    Remaining: 'المتبقي',
    status: 'الحالة',
    planning: 'التخطيط',
    active: 'نشط',
    onHold: 'معلق',
    completed: 'مكتمل',
    cancelled: 'ملغى',
    createProject: 'إنشاء مشروع',
      update: 'تحديث المشروع',
    project: 'المشروع',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    expectedCompletion: 'التاريخ المتوقع للانتهاء',
    budget: 'الميزانية',
    phaseName: 'اسم المرحلة',
    phaseNumber: 'رقم المرحلة',
    costCategory: 'فئة التكلفة',
    estimatedCost: 'التكلفة المقدرة',
    actualCost: 'التكلفة الفعلية',
    totalEstimatedCost: 'إجمالي التكلفة المقدرة',
    totalActualCost: 'إجمالي التكلفة الفعلية',
    variance: 'التفاوت',
    costStatus: 'حالة التكلفة',
    costDescription: 'وصف التكلفة',
    Estimated: 'مقدرة',
    Incurred: 'متكبدة',
    Paid: 'مدفوعة',
    category: 'الفئة',
    createPhase: 'إنشاء مرحلة',
    selectProject: 'اختر مشروع',
  },

  // Common Actions
  actions: {
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    view: 'عرض',
    add: 'إضافة',
    create: 'إنشاء',
    update: 'تحديث',
    confirm: 'تأكيد',
    close: 'إغلاق',
    submit: 'إرسال',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    import: 'استيراد',
  },

  // Messages
  messages: {
    loading: 'جاري التحميل...',
    success: 'تم بنجاح',
    error: 'حدث خطأ',
    confirmDelete: 'هل تأكد من الحذف؟',
    noData: 'لا توجد بيانات',
    emptyFields: 'يرجى ملء جميع الحقول المطلوبة',
  },
  customers: {
    customer:'عميل',
    customername:'اسم العميل',
    totalcustomers:'إجمالي العملاء',
    activecustomers:'العملاء النشطون',
    inactivecustomers:'العملاء غير النشطين',
    contactperson:'جهة الاتصال',
    totalsales:'إجمالي المبيعات',
    totalreceived:'إجمالي المستلم',
    totaloutstanding:'إجمالي المستحق',
    email:'البريد الإلكتروني',
    phone:'الهاتف',
    address:'العنوان',
    status:'الحالة',
    tax_id:'الرقم الضريبي',
    contact:'جهة الاتصال',
    actions:'الإجراءات',
    active:'نشط',
    inactive:'غير نشط',
    suspended:'معلق',
    title: 'العملاء',
    addCustomer: 'إضافة عميل',
    name: 'الاسم',
    contactPerson: 'جهة الاتصال',
   
  },
SalesInvoices:'فواتير المبيعات',
NewInvoice:'فاتورة جديدة',
SelectCustomer:'اختر العميل',
Paid:'المدفوع',
RecordPayment:'تسجيل الدفع',
Progress:'التقدم',
SalesReceivablesReports:'تقارير المبيعات والحسابات المستحقة',
CollectionRate:'معدل التحصيل',
CashFlowSummary:'ملخص التدفق النقدي',
AmountReceived:'المبلغ المستلم',
Outstanding:'المتبقي',
CustomerDistribution:'توزيع العملاء',
Cancel:'إلغاء',
edit:'تعديل',
delete:'حذف',




























};
